name: Build
on:
  push:
    branches:
      - "main"
permissions:
  contents: write
jobs:
  release-latest:
    runs-on: ubuntu-latest
    name: Latest master release
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: mv dist website
      - run: zip -r website.zip website
      - name: Remove previous "latest" release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release delete latest -y --cleanup-tag || true
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create "latest" -p website.zip
